[package]
name = "kohltastrophe/flux"
description = "Lazy fine-grained reactivity for Luau."
authors = ["Kohl <hi@kohl.gg>"]
version = "0.1.1"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["**"]
include = [
	"src",
	"src/**",
	"default.project.json",
	"wally.toml",
	"LICENSE.md",
]

[dependencies]
