name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Lint:
    environment: testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - uses: CompeyDev/setup-rokit@1d9390883f7ebce19d48f5b8d006e11d387c92ab
        with:
          version: "*"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check tool versions
        run: |
          rokit --version
          luau-lsp --version
          rojo --version
          stylua --version

      - name: Lint (analyze + format)
        run: .github/scripts/lint.sh

  Headless:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Install Luau
        run: |
          curl -sL https://github.com/luau-lang/luau/releases/download/0.724/luau-ubuntu.zip -o luau.zip
          unzip -o luau.zip luau
          chmod +x ./luau
          rm luau.zip

      - name: Run headless spec
        run: ./luau test/spec.luau

  Roblox:
    environment: testing
    runs-on: ubuntu-latest
    concurrency:
      group: luau-execution
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - uses: CompeyDev/setup-rokit@1d9390883f7ebce19d48f5b8d006e11d387c92ab
        with:
          version: "*"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run tests
        run: set -e && rojo build ./test/default.project.json --output dist.rbxl && python3 ./test/upload_and_run_task.py dist.rbxl $TEST_TASK_FILE && rm dist.rbxl
        env:
          ROBLOX_API_KEY: ${{ secrets.ROBLOX_API_KEY }}
          ROBLOX_UNIVERSE_ID: ${{ secrets.ROBLOX_TEST_UNIVERSE_ID }}
          ROBLOX_PLACE_ID: ${{ secrets.ROBLOX_TEST_PLACE_ID }}
          TEST_TASK_FILE: test/spec.luau
